export const BANK_LIST = [
    { code: '004', name: '臺灣銀行' },
    { code: '005', name: '土地銀行' },
    { code: '006', name: '合作金庫' },
    { code: '007', name: '第一銀行' },
    { code: '008', name: '華南銀行' },
    { code: '009', name: '彰化銀行' },
    { code: '011', name: '上海銀行' },
    { code: '012', name: '台北富邦' },
    { code: '013', name: '國泰世華' },
    { code: '015', name: '中國輸出' },
    { code: '016', name: '高雄銀行' },
    { code: '017', name: '兆豐銀行' },
    { code: '018', name: '農業金庫' },
    { code: '021', name: '花旗銀行' },
    { code: '048', name: '王道銀行' },
    { code: '050', name: '臺灣企銀' },
    { code: '052', name: '渣打銀行' },
    { code: '053', name: '台中銀行' },
    { code: '054', name: '京城銀行' },
    { code: '081', name: '滙豐銀行' },
    { code: '101', name: '瑞興銀行' },
    { code: '102', name: '華泰銀行' },
    { code: '103', name: '新光銀行' },
    { code: '108', name: '陽信銀行' },
    { code: '118', name: '板信銀行' },
    { code: '147', name: '三信銀行' },
    { code: '700', name: '中華郵政' },
    { code: '803', name: '聯邦銀行' },
    { code: '805', name: '遠東商銀' },
    { code: '806', name: '元大銀行' },
    { code: '807', name: '永豐銀行' },
    { code: '808', name: '玉山銀行' },
    { code: '809', name: '凱基銀行' },
    { code: '810', name: '星展銀行' },
    { code: '812', name: '台新銀行' },
    { code: '816', name: '安泰銀行' },
    { code: '822', name: '中國信託' },
    { code: '823', name: '將來銀行' },
    { code: '824', name: '連線銀行' },
    { code: '826', name: '樂天銀行' },
];

export const EXPENSE_CATEGORIES = [
    '保險費',
    '旅費',
    '廣告費',
    '交際費',
    '捐贈',
    '宜睿票券',
    '郵電費',
    '職工福利',
    '軟體使用費',
    '雜項購置',
    '租金支出',
    '文具用品'
];

export const EXPENSE_CATEGORY_MAP: Record<string, string> = {
    '保險費': 'Insurance',
    '旅費': 'Travel',
    '廣告費': 'Advertising',
    '交際費': 'Entertainment',
    '捐贈': 'Donation',
    '宜睿票券': 'Edenred_Ticket',
    '郵電費': 'Postage_Telecom',
    '職工福利': 'Employee_Welfare',
    '軟體使用費': 'Software_License',
    '雜項購置': 'Miscellaneous',
    '租金支出': 'Rent',
    '文具用品': 'Stationery'
};
